```{r}
# importing libraries
library(tidyr)
library(dplyr)
library(igraph)
library(harmonizer)
library(data.table)
library(styler)
library(lintr)

# reading data
sdc_data <- readRDS("SDC_data_2021.rds")

# preprocessing the participants and business description data
sdc_data$participants <- sdc_data$participants %>% 
                              harmonize.toascii(detect.encoding = FALSE) %>%  
                                harmonize.squish.spaces() %>% 
                                  harmonize.remove.brackets %>% 
                                    harmonize.toupper %>% 
                                      harmonize.squish.spaces(wrap.in.spaces = 
                                                                TRUE) %>% 
                                        cockburn.replace.punctuation %>% 
                                          harmonize.squish.spaces

```


```{r}
# this is for getting all the deal numbers later
biggest <- c("AP MOLLER MAERSK A S", "MSC MEDITERRANEAN SHIPPING CO", "COSCO SHIPPING CO LTD",
             "CMA CGM SA")

moller_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "AP MOLLER MAERSK A S"
                                    ) 

medit_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "MSC MEDITERRANEAN SHIPPING CO"
                                    ) 

cosco_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "COSCO SHIPPING CO LTD"
                                    ) 

cma_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "CMA CGM SA"
                                    ) 

```


```{r}
# cell for quickly checking data
temp_data <- sdc_data %>% filter(# status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %like% "YANG MING MARINE TRANSPORT"
                                    ) 

```


```{r}
# This part was created for Maersk but applied to other companies as well. 

m_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %like% "YANG MING MARINE TRANSPORT"
                                    # participants %like% "ORIENT OVERSEAS"
                                    # participants %like% "MAERSK A S"
                                    # participants == "AP MOLLER MAERSK A S"
                                    ) 
deal_nrs <- m_data$deal_number

# these are the first order connections
maersk_frst_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs
                                    )



maersk_2_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %in% unique(maersk_frst_data$participants)
                                    ) 



deal_nrs_scnd <- maersk_2_data$deal_number

# these are the second order connections
maersk_scnd_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_scnd
                                    ) 

# Maersk changed names during the time period
maersk_scnd_data$participants[maersk_scnd_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"

#removing IBM from the data (too big) (for the maersk network)
remove_2_IBM <- maersk_scnd_data[(maersk_scnd_data$participants == "IBM CORP"),]$deal_number
remove_2_NOVO <- maersk_scnd_data[(maersk_scnd_data$participants == "NOVO NORDISK A S"),]$deal_number

deal_nrs_no_big <- deal_nrs_scnd[!deal_nrs_scnd %in% remove_2_IBM]
deal_nrs_no_big <- deal_nrs_no_big[!deal_nrs_no_big %in% remove_2_NOVO]


maersk_scnd_no_big <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_no_big
                                    ) 



maersk_3_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %in% unique(maersk_scnd_no_big$participants)
                                    ) 

deal_nrs_thrd <- unique(maersk_3_data$deal_number)


maersk_thrd_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_thrd
                                    ) 

remove_3_IBM <- maersk_thrd_data[(maersk_thrd_data$participants == "IBM CORP"),]$deal_number
remove_3_NOVO <- maersk_thrd_data[(maersk_thrd_data$participants == "NOVO NORDISK A S"),]$deal_number

deal_nrs_no_big <- deal_nrs_thrd[!deal_nrs_thrd %in% remove_3_IBM]
deal_nrs_no_big <- deal_nrs_no_big[!deal_nrs_no_big %in% remove_3_NOVO]

# these are the third order connections excluding IBM and NOVO NORDISK
maersk_thrd_no_big <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_no_big
                                    ) 

```


```{r}
# cell for getting first and second connections of the top 4 shipping companies
deal_nrs <- unique(c(cma_data$deal_number, moller_data$deal_number, cosco_data$deal_number, cma_data$deal_number))

first_conn_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    deal_number %in% deal_nrs 
                                    ) 

second_conn <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %in% first_conn_data$participants
                                    ) 

deal_nrs_two <- second_conn$deal_number

second_conn_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    deal_number %in% deal_nrs_two
                                    ) 

```


```{r}
# for loop for the network over time. Starting at 1997 when the first connection is formed

for (year in 2020:2022) {
  print(year)
  moller_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < as.character(year),
                                    participants %like% "MAERSK A S"
                                    ) 
  
  medit_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < as.character(year),
                                      participants %like% "MSC MEDITERRANEAN SHIPPING CO"
                                      ) 
  

  cosco_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < as.character(year),
                                      participants %like% "COSCO SHIPPING CO LTD"
                                      ) 
  

  cma_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < as.character(year),
                                      participants %like% "CMA CGM SA"
                                      ) 
  
  cma_data$participants[cma_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"
  
  # taking all first connections and combining them into 1 vector
  deal_nrs <- unique(c(cma_data$deal_number, moller_data$deal_number, cosco_data$deal_number, cma_data$deal_number))

  first_conn_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < "2022",
                                      deal_number %in% deal_nrs
                                      ) 
  first_conn_data$participants[first_conn_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"
  
  
  data_net <- first_conn_data %>% select(participants, deal_number)
  
  # creating the adjacency matrix
  data_matrix <- as.matrix(table(data_net)) %*% 
                          t(as.matrix(table(data_net)))
  
  # creating graph object
  grap <- graph_from_adjacency_matrix(
    data_matrix,
    mode = "undirected",
    # mode = c("directed", "undirected", "max", "min", "upper", "lower", "plus"),
    weighted = "max",
    diag = FALSE,
    add.colnames = NULL,
    add.rownames = NA
  )
  
  # saving output for the report (uncommend this and line 303 if you want output)
  # jpeg(paste0(year,".jpeg"), width=15, height=15, units="in", res=300)
  
  #plotting graph object
  plot(grap,
       # main = paste0("until year ", year),
       cex=5,
       vertex.label.cex = 1,
       vertex.label.font = 2,
       # vertex.label = NA,
       vertex.label.color = "black",
       vertex.size = 8
       )
  title(main=paste0("until year ", year), cex.main=4)
  
  # dev.off()
}

# open graphs in new window to get a better overview
```


```{r}
# used this cell for checking other companies second or third connection networks
data_net <- maersk_scnd_data %>% select(participants, deal_number)

data_matrix <- as.matrix(table(data_net)) %*% 
                        t(as.matrix(table(data_net)))

grap <- graph_from_adjacency_matrix(
  data_matrix,
  mode = "undirected",
  weighted = "max",
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)


plot(grap,
     vertex.label.cex = 1,
     vertex.label.font = 2,
     # vertex.label = NA,
     vertex.label.color = "black",
     vertex.size = 8
     )
title(main=paste0("YANG MING MARINE TRANSPORT"), cex.main=4)
```






















