```{r}
library(tidyr)
library(dplyr)
library(igraph)
library(harmonizer)
library(data.table)
sdc_data <- readRDS("SDC_data_2021.rds")
orbis_data <- read.csv("cleaned_orbis_data.csv", sep = ";")
sdc_data$participants <- sdc_data$participants %>% 
                              harmonize.toascii(detect.encoding = FALSE) %>%  
                                harmonize.squish.spaces() %>% 
                                  harmonize.remove.brackets %>% 
                                    harmonize.toupper %>% 
                                      harmonize.squish.spaces(wrap.in.spaces = 
                                                                TRUE) %>% 
                                        cockburn.replace.punctuation %>% 
                                          harmonize.squish.spaces
sdc_data$business_description <- sdc_data$business_description %>% 
                              harmonize.toascii(detect.encoding = FALSE) %>%  
                                harmonize.squish.spaces() %>% 
                                  harmonize.remove.brackets %>% 
                                    harmonize.toupper %>% 
                                      harmonize.squish.spaces(wrap.in.spaces = 
                                                                TRUE) %>% 
                                        cockburn.replace.punctuation %>% 
                                          harmonize.squish.spaces
# https://www.r-graph-gallery.com/248-igraph-plotting-parameters.html <- for graphs
```

```{r}
biggest <- c("AP MOLLER MAERSK A S", "MSC MEDITERRANEAN SHIPPING CO", "COSCO SHIPPING CO LTD",
             "CMA CGM SA")
moller_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    # participants == "SHELL OIL CO",
                                    participants %like% "AP MOLLER MAERSK A S"
                                    ) 
medit_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "MSC MEDITERRANEAN SHIPPING CO"
                                    ) 
cosco_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "COSCO SHIPPING CO LTD"
                                    ) 
cma_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %like% "CMA CGM SA"
                                    ) 
```


```{r}
terminated_data <- sdc_data %>% filter(
  # date_terminated != ""
  status == "Terminated"
                                    ) 
```


```{r}
energ_data <- sdc_data %>% filter(
                                    # status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %like% "YANG MING MARINE TRANSPORT"
       
                                    
                                                 ) 
m_data$participants <- "AP MOLLER MAERSK A S"
maersk_scnd_data
```


```{r}
# MAERSK
# `%notin%` <- Negate(`%in%`)
m_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    #participants %like% "YANG MING MARINE TRANSPORT"
                                     participants %like% "ORIENT OVERSEAS"
                                    # participants %like% "MAERSK A S"
                                    # participants == "AP MOLLER MAERSK A S"
                                    ) 
deal_nrs <- m_data$deal_number
maersk_frst_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs
                                    )
maersk_2_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %in% unique(maersk_frst_data$participants)
                                    ) 
deal_nrs_scnd <- maersk_2_data$deal_number
maersk_scnd_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_scnd
                                    ) 
maersk_scnd_data$participants[maersk_scnd_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"
#removing IBM from the data (too big)
remove_2_IBM <- maersk_scnd_data[(maersk_scnd_data$participants == "IBM CORP"),]$deal_number
remove_2_NOVO <- maersk_scnd_data[(maersk_scnd_data$participants == "NOVO NORDISK A S"),]$deal_number
deal_nrs_no_big <- deal_nrs_scnd[!deal_nrs_scnd %in% remove_2_IBM]
deal_nrs_no_big <- deal_nrs_no_big[!deal_nrs_no_big %in% remove_2_NOVO]
maersk_scnd_no_big <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_no_big
                                    ) 
maersk_3_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    participants %in% unique(maersk_scnd_no_big$participants)
                                    ) 
deal_nrs_thrd <- unique(maersk_3_data$deal_number)
maersk_thrd_data <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_thrd
                                    ) 
remove_3_IBM <- maersk_thrd_data[(maersk_thrd_data$participants == "IBM CORP"),]$deal_number
remove_3_NOVO <- maersk_thrd_data[(maersk_thrd_data$participants == "NOVO NORDISK A S"),]$deal_number
deal_nrs_no_big <- deal_nrs_thrd[!deal_nrs_thrd %in% remove_3_IBM]
deal_nrs_no_big <- deal_nrs_no_big[!deal_nrs_no_big %in% remove_3_NOVO]
maersk_thrd_no_big <- sdc_data %>% filter(
                                    status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < "2022",
                                    deal_number %in% deal_nrs_no_big
                                    ) 
```

```{r}
deal_nrs_thrd
```


```{r}
deal_nrs <- unique(c(cma_data$deal_number, moller_data$deal_number, cosco_data$deal_number, cma_data$deal_number))
first_conn_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    deal_number %in% deal_nrs 
                                    ) 
```


```{r}
# second tier
# parts_two <- unique(first_conn_data$participants)
# parts_two <- unique()
second_conn <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    participants %in% parts_two
                                    ) 
deal_nrs_two <- second_conn$deal_number
second_conn_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1964-01-01",
                                    date_announced < "2021-09-15",
                                    deal_number %in% deal_nrs_two
                                    ) 
```

```{r}
data <- first_conn_data
data$color <- "red"
data$biggest <- NA
seen <- c()
`%notin%` <- Negate(`%in%`)
for (r in 1:nrow(data)) {
  if (data[r, "participants"] %in% biggest) {
    data[r, "color"] <- "blue"
    data[r, "biggest"] <- data[r, "participants"]
    # if (data[r, "participants"] %notin% seen) {
    #   seen <- append(data[r, "participants"], seen)
    #   data[r, "biggest"] <- data[r, "participants"]
    # }
    
    
  }
}
data_net <- data %>% select(participants, deal_number)
data_graph <- as.matrix(table(data_net)) %*% t(as.matrix(table(data_net))) %>%
                          graph_from_adjacency_matrix(mode = "undirected")
data_graph <- simplify(data_graph, remove.loops = TRUE, 
                               remove.multiple = TRUE)
set.seed(1)
plot(data_graph, 
     main= paste('Until year', as.character(2022)),
     layout = layout_in_circle(data_graph), 
     vertex.label.font = 4,
     vertex.size = 10,
     vertex.label = NA,
     vertex.label.dist=1.5,
     edge.width = 1, 
     edge.color = "black")
# plot(data_graph, 
#      layout = layout_in_circle(data_graph), 
#      # vertex.color = data$color, 
#      # vertex.label = data$participants, 
#      vertex.label = NA,
#      # vertex.label.font = 4,
#      vertex.size = 10, 
#      edge.width = 1, 
#      vertex.label.dist=1.5,
#      edge.color = "black")
```

Ying 

```{r}
for (year in 1997:2022) {
  print(year)
  moller_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                    date_terminated == "",
                                    date_announced > "1963",
                                    date_announced < as.character(year),
                                    participants %like% "MAERSK A S"
                                    ) 
  
  medit_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < as.character(year),
                                      participants %like% "MSC MEDITERRANEAN SHIPPING CO"
                                      ) 
  
  cosco_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < as.character(year),
                                      participants %like% "COSCO SHIPPING CO LTD"
                                      ) 
  
  cma_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < as.character(year),
                                      participants %like% "CMA CGM SA"
                                      ) 
  
  cma_data$participants[cma_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"
  
  
  deal_nrs <- unique(c(cma_data$deal_number, moller_data$deal_number, cosco_data$deal_number, cma_data$deal_number))
  first_conn_data <- sdc_data %>% filter(status == "Completed/Signed", 
                                      date_terminated == "",
                                      date_announced > "1963",
                                      date_announced < "2022",
                                      deal_number %in% deal_nrs
                                      ) 
  first_conn_data$participants[first_conn_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"
  
  data_net <- first_conn_data %>% select(participants, deal_number)
  
  data_matrix <- as.matrix(table(data_net)) %*% 
                          t(as.matrix(table(data_net)))
  
  data_graph <- igraph::graph.incidence(data_matrix)
  
  
  data_graph <- simplify(data_graph, remove.loops = TRUE, 
                                 remove.multiple = TRUE)
  
  grap <- graph_from_adjacency_matrix(
    data_matrix,
    mode = "undirected",
    # mode = c("directed", "undirected", "max", "min", "upper", "lower", "plus"),
    weighted = "max",
    diag = FALSE,
    add.colnames = NULL,
    add.rownames = NA
  )
  
  jpeg(paste0(year,".jpeg"), width=15, height=15, units="in", res=300)
  
  plot(grap,
       # main = paste0("until year ", year),
       cex=5,
       vertex.label.cex = 1,
       vertex.label.font = 2,
       # vertex.label = NA,
       vertex.label.color = "black",
       vertex.size = 8
       # ,vertex.label.dist=1
       # ,vertex.size = ifelse(igraph::V(journalists_net)$type == FALSE, 16, 6)
       )
  title(main=paste0("until year ", year), cex.main=4)
  dev.off()
}
```

```{r}
journalists <- read.csv("journalists-edges.csv", 
                        header = TRUE, row.names = 1) 
journalists_attr <- read.csv("journalists-nodes.csv", 
                             header = TRUE, 
                             as.is = TRUE)
journalists_net <- igraph::graph.incidence(journalists)
```

```{r}
year <- 0
paste0("until year ", year)
```

```{r}
igraph::V(journalists_net)$color <- hcl.colors(2)[as.factor(igraph::V(journalists_net)$type)]
igraph::V(journalists_net)$shape <- ifelse(igraph::V(journalists_net)$type == TRUE, "circle", "square")
# 
# # News agencies will have name labels, journalists will not:
igraph::V(journalists_net)$label <- ifelse(igraph::V(journalists_net)$type == FALSE,
                                           journalists_attr$name[igraph::V(journalists_net)$type == FALSE],
                                           NA)
plot(journalists_net, 
     vertex.label.cex = 0.6,
     vertex.label.font = 2, 
     vertex.label.color = "white"
     # ,vertex.size = ifelse(igraph::V(journalists_net)$type == FALSE, 16, 6)
     )
```

```{r}
journalists
```



```{r}
data_net <- maersk_scnd_data %>% select(participants, deal_number)
data_matrix <- as.matrix(table(data_net)) %*% 
                        t(as.matrix(table(data_net)))
# diag(data_matrix) <- 0
# data_matrix[data_matrix > 1.1] <- 1
# data_matrix[lower.tri(data_matrix)] <- 0
data_graph <- igraph::graph.incidence(data_matrix)
data_graph <- simplify(data_graph, remove.loops = TRUE, 
                               remove.multiple = TRUE)
grap <- graph_from_adjacency_matrix(
  data_matrix,
  mode = "undirected",
  # mode = c("directed", "undirected", "max", "min", "upper", "lower", "plus"),
  weighted = "max",
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)
# pdf("graphopt.pdf", height = 14, width = 14)
plot(grap,
     # main = "hello",
     vertex.label.cex = 0.8,
     vertex.label.font = 2,
     # vertex.label = NA,
     vertex.label.color = "black",
     vertex.size = 8,
     edge.width = 1
     # ,vertex.size = ifelse(igraph::V(journalists_net)$type == FALSE, 16, 6)
     )
# dev.off()
```

```{r}
maersk_frst_data$participants[maersk_frst_data$participants == "MAERSK A S"] <- "AP MOLLER MAERSK A S"
maersk_frst_data
```


```{r}
data_net <- maersk_scnd_data %>% select(participants, deal_number)
data_matrix <- as.matrix(table(data_net)) %*% 
                        t(as.matrix(table(data_net)))
# diag(data_matrix) <- 0
# data_matrix[data_matrix > 1.1] <- 1
# data_matrix[lower.tri(data_matrix)] <- 0
data_graph <- igraph::graph.incidence(data_matrix)
data_graph <- simplify(data_graph, remove.loops = TRUE, 
                               remove.multiple = TRUE)
grap <- graph_from_adjacency_matrix(
  data_matrix,
  mode = "undirected",
  # mode = c("directed", "undirected", "max", "min", "upper", "lower", "plus"),
  weighted = "max",
  diag = FALSE,
  add.colnames = NULL,
  add.rownames = NA
)
 jpeg("ORIENT OVERSEAS.jpeg", width=15, height=15, units="in", res=300)
plot(grap,
     vertex.label.cex = 1,
     vertex.label.font = 2,
     # vertex.label = NA,
     vertex.label.color = "black",
     vertex.size = 8
     ,vertex.color = ifelse(igraph::V(data_graph)$name == "ORIENT OVERSEASLTD" | igraph::V(data_graph)$name == "ORIENT OVERSEAS CONTAINER LINE" , "#F394FD", "#F4D03F")
        ,vertex.shape = ifelse(igraph::V(data_graph)$name == "ORIENT OVERSEASLTD" | igraph::V(data_graph)$name == "ORIENT OVERSEAS CONTAINER LINE" , "square", "circle")
     )
title(main=paste0("ORIENT OVERSEAS"), cex.main=4)
# dev.off()
```

```{r}
data_net$participants
```
